name: Makefile 

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  build:

    runs-on: visual studio code-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
